version: "3.9"

services:
  calisim:
    image: ghcr.io/plant-food-research-open/calisim-examples-workshop:${CALISIM_VERSION:-latest}
    command: sleep infinity
    volumes:
      - .:/workspace
    tty: true
